import Head from 'next/head'
import Cards from '../components/Cards'
import Footer from '../components/Footer'
import Header from '../components/Header'
import styles from '../styles/Home.module.scss'
import ColorButton from '../components/ColorButton'
import { useEffect, useState } from 'react'

export default function Home() {
  const [theme, setTheme] = useState('dark-theme')

  useEffect(() => {
    document.body.className = theme
  }, [theme])

  return (
    <div className={ styles.home }>
      <ColorButton
        theme={ theme }
        setTheme={ setTheme }
      />
      <Head>
        <title>Kemal Cetmen</title>
        <meta name="description" content="Generated by Kemal C" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Cards />
      <Footer />
    </div>
  )
}
